# Generated by Django 4.2 on 2023-04-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.CharField(default='beginner', max_length=20),
        ),
    ]
